pipeline {
    agent any
    environment {
        FRONT_IMG = "book-lib-ai-frontend:local"
    }
    stages {
        stage('拉取代码') {
            steps {
                git url: 'https://github.com/liuyh-art/book-lib-ai.git',
                branch: 'main',
                credentialsId: 'github-ssh'
            }
        }
        stage('本地构建前端镜像') {
            steps {
                sh '''
                cd frontend
                docker build -t $FRONT_IMG .
                '''
            }
        }
        stage('启动前端容器') {
            steps {
                sh '''
                docker stop frontend || true
                docker rm frontend || true
                docker run -d -p "80:80" --network book_net --name frontend $FRONT_IMG
                '''
            }
        }
    }
    post {
        success { echo "前端单独部署完成" }
        failure { echo "前端部署失败" }
    }
}