pipeline {
    agent any
    environment {
        BACK_IMG = "book-lib-ai-backend:local"
    }
    stages {
        stage('拉取代码') {
            steps {
                 git url: 'https://github.com/liuyh-art/book-lib-ai.git',
                 branch: 'main',
                 credentialsId: 'github-ssh'
            }
        }
        stage('本地构建后端镜像') {
            steps {
                powershell '''
                cd backend
                docker build -t ${env.BACK_IMG} .
                '''
            }
        }
        stage('启动后端容器') {
            steps {
                powershell '''
                docker network inspect book_net > $null 2>&1 || docker network create book_net
                docker stop backend || true
                docker rm backend || true
                docker run -d -p "8081:8081" --network book_net --add-host=host.docker.internal:host-gateway --name backend ${env.BACK_IMG}
                '''
            }
        }
    }
    post {
        success { echo "后端单独部署完成" }
        failure { echo "后端部署失败" }
    }
}